### ISSUE TITLE
MapStore metadata pop-up does not always retrieve the URL from the GeoNetwork metadata sheet

### ISSUE THREAD

**Issue by severinmenard** [georchestra/mapstore2-georchestra#335]
Context : MapStore for geOrchestra, last update on January 29th

I created [this map](https://ifl.francophonelibre.org/mapstore/#/viewer/openlayers/267) with an external layer (“Arbres d’alignement”) and one of my pg layers (“Lieux de culte - Bouaké)

The pop-up metadata of the external layer displays well the URL of the GeoNetwork file (so this is not a problem with the configuration files of my geOrchestra instance):
![Fiche_MD_MapStore_avec_URL_vers_GN](https://user-images.githubusercontent.com/1291055/108856212-947c1180-75c8-11eb-8712-4d877ac368f6.png)

while it does not appear on my pg layer ([here](https://ifl.francophonelibre.org/geonetwork/srv/fre/catalog.search#/metadata/bb788df8-2ad8-41b7-b6ad-25445fc8ecc7) is the link of the metadata page)
![Fiche_MD_MapStore_sans_URL_vers_GN](https://user-images.githubusercontent.com/1291055/108856317-b1b0e000-75c8-11eb-964e-c757fbdc5486.png)

I wonder if this is an issue related to:
- MapStore requires a specific metadata template
- a security restriction in the access of MapStore to GeoNetwork on my server

**Comment by MaelREBOUX** [comment]
Hello @severinmenard 

Same question as here  https://github.com/georchestra/mapstore2-georchestra/issues/300#issuecomment-859524716

Maybe is it fixed now ?

**Comment by severinmenard** [comment]
Hello @MaelREBOUX 
Unfortunately no, I think @pierrejego tried to fix it

**Comment by severinmenard** [comment]
The question is actually a bit different from #300 because here there is a layer from another instance than mine that succeeds to get the URL of the GeoNetwork metadata page, while I never managed to get this. In #300 I explain than any layer added in MapStore through GeoServer (and not the MapStore catalog) does not have metadata at all when clicking on the MapStore metadata layer button

**Comment by severinmenard** [comment]
The issue is still here (geOrchestra has been updated on January 28, 2021 with v2021.01.00. GeoServer is v 2.17). @pierrejego had the same issues with his own layers. Would you recommend to upgrade to 20.1.1? The list of bug fixes dos not seem to have something about this.

**Comment by MaelREBOUX** [comment]
Well... We are here currently working with geOrchestra 20.1.1 and for me all is good on metadata urls / access.
